bpm:
  file-path: /Users/jiez/Downloads
  ctx: ''
  target-url: http://127.0.0.1:9888
  type: 1
  callback-url: http://127.0.0.1:9888/bill/rest/callback
  pushmsg-url: http://127.0.0.1:9888/task/pushmsg
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.jdbc.Driver
      #      url: jdbc:mysql://127.0.0.1:3306/haosen_srm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      #      username: root
      #      password: root
      url: jdbc:mysql://122.112.238.141:3306/haosen_srm?useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
      username: dev
      password: JtXingYun!2019
      initial-size: 10
      max-active: 20
      min-idle: 2
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM uc_user
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
    timeout: 30s
  boot:
    admin:
      client:
        url: http://127.0.0.1:9095
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/infra/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.**.**.infra.entity
  type-enums-package: com.**.**.infra.entity.enums
  type-handlers-package: com.**.**.infra.entity.typehandler
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    # 配置type-enums-package只对注解方式的枚举处理能提前加载缓存.
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
logging:
  level:
    root: info
    com.jingtong: debug