scis:
  tenant:
    enable: false
bpm:
  file-path: /Users/jiez/workspace/haosen/haosen_srm/media
  ctx: ''
  target-url: http://127.0.0.1:8778
  type: 1
  callback-url: http://127.0.0.1:8778/bill/rest/callback
  pushmsg-url: http://127.0.0.1:8778/task/pushmsg
server:
  port: 9094
spring:
  application:
    name: bpm-server
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  #环境 dev|test|prod
  profiles:
    active: prod
  messages:
    encoding: UTF-8
    basename: i18n/messages_common
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /view/
      suffix: .ftl
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/view/, classpath:/templates/*
    cache: false
  activiti:
    async-executor-activate: true
    check-process-definitions: false
    jpaEnabled: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://119.3.5.90:3306/jqh_srm_9001?useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
      username: root
      password: Jingtong@2021
      initial-size: 10
      max-active: 20
      min-idle: 2
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM uc_user
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
    timeout: 30s
  boot:
    admin:
      client:
        url: http://127.0.0.1:9095
management:
  server:
    port: -1
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    com.srm: debug
    com.srm.bpm.infra.dao.ToaBillDao.selectTodoSizeByStatus: error
    de.codecentric.boot.admin.client.registration: off
feign:
  sentinel:
    enabled: true
ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 300000
logbook:
  execution: execution(* com.srm.bpm.facade.*.*Controller.*(..))
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/infra/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.**.**.infra.entity
  type-enums-package: com.**.**.infra.entity.enums
  type-handlers-package: com.**.**.infra.entity.typehandler
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    # 配置type-enums-package只对注解方式的枚举处理能提前加载缓存.
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
seata:
  enabled: false
  tx-service-group: bpm_tx_group
  enable-auto-data-source-proxy: false
  transport:
    type: tcp
    server: nio
    heartbeat: true
    enable-client-batch-send-request: true
    thread-factory:
      boss-thread-prefix: 'NettyBoss'
      worker-thread-prefix: 'NettyServerNIOWorker'
      server-executor-thread-prefix: 'NettyServerBizHandler'
      share-boss-worker: false
      client-selector-thread-prefix: 'NettyClientSelector'
      client-selector-thread-size: 1
      client-worker-thread-prefix: 'NettyClientWorkerThread'
      boss-thread-size: 1
      worker-thread-size: default
    shutdown:
      wait: 3
    serialization: seata
    compressor: none
  service:
    default:
      grouplist: "127.0.0.1:8091"
    enable-degrade: false
    disable-global-transaction: false
    vgroup-mapping:
      bpm_tx_group: 'default'
  client:
    rm:
      async-commit-buffer-limit: 10000
      lock:
        retry-interval: 10
        retry-times: 30
        retry-policy-branch-rollback-on-conflict: true
    tm:
      commit-retry-count: 5
      rollback-retry-count: 5
    undo:
      log-table: 'undo_log'
      log-serialization: jackson
      data-validation: true
  log:
    exception-rate: 100
